# https://school.programmers.co.kr/learn/courses/30/lessons/59045

# SELECT  ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.ANIMAL_TYPE, ANIMAL_INS.NAME
#
# FROM ANIMAL_INS
#
# LEFT OUTER JOIN ANIMAL_OUTS
#
# on ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
#
# where (ANIMAL_INS.SEX_UPON_INTAKE = "Intact Male" or ANIMAL_INS.SEX_UPON_INTAKE = "Intact Female")
# and (ANIMAL_OUTS.SEX_UPON_OUTCOME = "Spayed Female" or ANIMAL_OUTS.SEX_UPON_OUTCOME = "Neutered Male")
#
# ORDER BY ANIMAL_ID